# Generated by Django 6.0.4 on 2026-04-25 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('education', '0003_alter_teachergroup_options_group_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='education.group'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casesubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='casesubmission',
            unique_together={('student', 'case')},
        ),
    ]
