# Generated by Django 6.0.4 on 2026-04-25 05:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_assignment_options_alter_casestudy_options_and_more'),
        ('education', '0003_alter_teachergroup_options_group_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyresult',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casestudyresult',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='coin_reward',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='xp_reward',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='coin_reward',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='test',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.group'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='education.group'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('test', 'student')},
        ),
        migrations.DeleteModel(
            name='CaseStudy',
        ),
        migrations.DeleteModel(
            name='CaseStudyResult',
        ),
    ]
