# Generated by Django 6.0.4 on 2026-04-25 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_teachergroup_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachergroup',
            options={'ordering': ['group__name'], 'verbose_name': 'Teacher Group', 'verbose_name_plural': 'Teacher Groups'},
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teachergroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
